version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_container
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always

  chatbot:
    build: .
    container_name: chatbot_container
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    ports:
      - "8501:8501"  # Streamlit runs on port 8501
    restart: always
